language: ruby
sudo: false
os:
  - linux
  - osx
cache:
  bundler
env:
  matrix:
    - EMACS_VERSION=24.5
#   - EMACS_VERSION=25.1-rc2
    - EMACS_VERSION=25.1
#    - TEXINFO_VERSION=6.1
before_install:
  - export PATH="$HOME/bin:$PATH"
script:
  - if [[ -n $EMACS_VERSION ]]; then make -f emacs-travis.mk install_emacs; fi
  - if [[ -n $TEXINFO_VERSION ]]; then make -f emacs-travis.mk install_texinfo; fi
  - make -f emacs-travis.mk test
